name: "Setup Incus"
author: bdx0
description: setup Incus on GitHub Runner in Ubuntu
branding:
  icon: package
  color: blue

inputs:
  incus_version:
    required: false

runs:
  using: composite
  steps:
    - name: Check platform
      run: if [[ "${{ runner.os }}" != "Linux" ]]; then echo "::error::Unsupported platform - ${{ runner.os }}"; exit 1; fi
      shell: bash
    - name: Install incus
      shell: bash
      run: |
        curl https://pkgs.zabbly.com/get/incus-stable | sudo sh -x

    - name: Reset the firewall
      shell: bash
      run: |
        sudo nft flush ruleset

    - name: Init incus
      shell: bash
      run: |
        sudo incus admin waitready
        sudo incus admin init --auto
        sudo usermod -aG incus-admin $USER

    # - name: Check normal user can accessiable to incus daemon.
    #   shell: bash
    #   run: |
    #     newgrp incus-admin
    #     id
    #     incus ls # check in accessiable

    # - name: Configure firewall
    #   shell: bash
    #   run: |
    #     set -x
    #     sudo iptables -I DOCKER-USER -i lxdbr0 -j ACCEPT
    #     sudo iptables -I DOCKER-USER -o lxdbr0 -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT
