name: "Setup Incus"
author: bdx0
description: setup Incus on GitHub Runner in Ubuntu
branding:
  icon: package
  color: blue

inputs:
  incus_version:
    required: false

runs:
  using: composite
  steps:
    - name: Check platform
      run: if [[ "${{ runner.os }}" != "Linux" ]]; then echo "::error::Unsupported platform - ${{ runner.os }}"; exit 1; fi
      shell: bash
    - name: Install incus
      run: |
        curl https://pkgs.zabbly.com/get/incus-stable | sudo sh -x

    - name: Reset the firewall
      run: |
        sudo nft flush ruleset

    - name: Init incus
      shell: bash
      run: |
        sudo incus waitready
        sudo incus admin init --auto
        sudo usermod -aG incus-admin $USER
        incus ls # check in accessiable

    - name: Configure firewall
      shell: bash
      run: |
        set -x
        sudo iptables -I DOCKER-USER -i lxdbr0 -j ACCEPT
        sudo iptables -I DOCKER-USER -o lxdbr0 -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT
