name: "Run archbox from Incus"
on: [push, pull_request, workflow_dispatch]
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Setup LXD
        uses: bdx0/action-incus@v1

      - name: Launch container
        run: |
          sudo incus launch images:ubuntu/22.04 u1

      - name: Launch an arch container
        run: sudo incus launch images:b0b987c75be9 archbox

      - name: Instlal ansible in this box
        run: |
          sleep 10
          sudo incus exec archbox -- pacman -Syu ansible --noconfirm
