name: "User action-incus to run ubuntu images from incus"
on: [push, pull_request, workflow_dispatch]
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Setup LXD
        uses: bdx0/action-incus@v1

      - name: Launch container
        run: |
          sudo incus launch images:ubuntu/22.04 u1
