name: "Test action-incus"
on:
  push:
  pull_request:
jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - ubuntu-20.04
          - ubuntu-18.04
          - ubuntu-16.04
        incus_version:
          - latest
    steps:
      - uses: actions/checkout@v4
      - name: Run ${{ github.repository }}@${{ github.sha }}
        uses: ./
        with:
          incus_version: ${{ matrix.incus_version}}
      - name: Launch instance
        run: sudo incus launch images:ubuntu/focal instance
      - name: Check network connectivity
        run: |
          sleep 20  # wait to attach ip address
          sudo incus exec instance -- dig google.com +short
          sudo incus exec instance -- curl https://github.com
      - name: Show information of storage and network
        run: |
          echo "incus storage list"
          sudo incus storage list
          echo "incus storage info default"
          sudo incus storage info default
          echo "incus network list"
          sudo incus network list
          echo "incus network info incusbr0"
          sudo incus network info incusbr0
